From fred@redhotpenguin.com Thu Aug 10 20:30:41 2006 -0700
Status: R
X-Status: 
X-Keywords:
Return-Path: <jeff@leknott.com>
Delivered-To: fred@redhotpenguin.com
Received: (qmail 20919 invoked by uid 1005); 10 Aug 2006 20:30:41 -0700
X-Spam-Status: No, hits=-2.6 required=5.0
	tests=AWL,BAYES_00
X-Spam-Check-By: app.redhotpenguin.com
Received: from iserv2.mycingular.net (HELO iserv2.mycingular.net) (66.209.10.202)
    by app.redhotpenguin.com (qpsmtpd/0.31.1) with ESMTP; Thu, 10 Aug 2006 20:30:39 -0700
Received: from xmweb03fe (xmweb01.mycingular.net [66.209.10.41])
	by iserv2.mycingular.net (8.13.6/8.13.6) with SMTP id k7B3Uapa029164
	for <fred@redhotpenguin.com>; Thu, 10 Aug 2006 22:30:36 -0500 (CDT)
Message-Id: <200608110330.k7B3Uapa029164@iserv2.mycingular.net>
Date: Thu, 10 Aug 2006 23:30:36 EDT
Subject: Fwd: [SL] Re: Del.icio.us Bug
From: "Jeff Lennan" <jeff@leknott.com>
To: fred@redhotpenguin.com
CC: 
MIME-Version: 1.0
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Mailer: Seven Enterprise Gateway (v 2.0)

Ping

-----Original Message-----
From: Fred Moyer <do-not-reply-C3271061@prdf.clientsection.com>
Sent: Thu, 10 Aug 2006 14:22:51 Central Daylight Time
To: Jeff Lennan <jeff@redhotpenguin.com>
Subject: [SL] Re: Del.icio.us Bug

A new comment has been posted. DO NOT REPLY TO THIS EMAIL.
To post your own comment or read the original message, visit:
http://prdf.clientsection.com/P3090176

-----------------------------------------------------------------
Company: Silver Lining
Project: QA
-----------------------------------------------------------------
Fred Moyer posted this comment:
.................................................................

   Scratch the cc approach, we scrub the recipient list as we should.
   Please forward a copy to me instead.

   - comment posted via summit (http://summit.redhotpenguin.com)

--
DO NOT REPLY TO THIS EMAIL
To post a comment of your own, read the original message, or to
read all existing comments, visit:
http://prdf.clientsection.com/C3271061



