From fred@redhotpenguin.com Thu Aug 10 18:08:22 2006 -0700
Return-Path: <garrettsuchecki@gmail.com>
Delivered-To: fred@redhotpenguin.com
Received: (qmail 18695 invoked by uid 1005); 10 Aug 2006 18:08:22 -0700
X-Spam-Status: No, hits=-2.4 required=5.0
	tests=AWL,BAYES_00,DNS_FROM_RFC_ABUSE
X-Spam-Check-By: app.redhotpenguin.com
Received: from py-out-1112.google.com (HELO py-out-1112.google.com) (64.233.166.181)
    by app.redhotpenguin.com (qpsmtpd/0.31.1) with ESMTP; Thu, 10 Aug 2006 18:08:21 -0700
Received: by py-out-1112.google.com with SMTP id i49so992246pyi
        for <fred@redhotpenguin.com>; Thu, 10 Aug 2006 18:08:19 -0700 (PDT)
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
        s=beta; d=gmail.com;
        h=received:message-id:date:from:user-agent:mime-version:to:subject:content-type;
        b=pDNZTsueyqBTVyjiNLtPvDkXkVKqBOZCXkDd4Vk7KaPPR/IKiiO8A2RN2Ka8GLNXNMF6Ff/AaPd2QJc2LApknh9Ryys2Go4VJ4jJhLXxWr7iSdqp3bdeCLsGfKuz5/1v6TLpuKReusRx9ycA0qteE+TY5Yq2RWNfd8iFGWU0dAM=
Received: by 10.65.51.16 with SMTP id d16mr3336475qbk;
        Thu, 10 Aug 2006 18:08:08 -0700 (PDT)
Return-Path: <garrettsuchecki@gmail.com>
Received: from ?192.168.1.100? ( [69.45.19.79])
        by mx.gmail.com with ESMTP id q16sm1133426qbq.2006.08.10.18.08.08;
        Thu, 10 Aug 2006 18:08:08 -0700 (PDT)
Message-ID: <44DBD875.8040109@gmail.com>
Date: Thu, 10 Aug 2006 18:08:05 -0700
From: Garrett Suchecki <garrettsuchecki@gmail.com>
User-Agent: Thunderbird 1.5.0.5 (Windows/20060719)
MIME-Version: 1.0
To: Fred Moyer <fred@redhotpenguin.com>
Subject: [Fwd: [SL] Re: Del.icio.us Bug]
Content-Type: multipart/mixed;
 boundary="------------030908080909060200020902"
Status: RO
X-Status: A
X-Keywords: NonJunk        
X-UID: 1

This is a multi-part message in MIME format.
--------------030908080909060200020902
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

this is where my post would be.

--------------030908080909060200020902
Content-Type: message/rfc822;
 name="[SL] Re: Del.icio.us Bug"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="[SL] Re: Del.icio.us Bug"

X-Account-Key: account2
X-Gmail-Received: fc000f8dc4e046e143a5f580e0d325da5448547e
Delivered-To: garrettsuchecki@gmail.com
Received: by 10.65.113.2 with SMTP id q2cs64798qbm;
        Thu, 10 Aug 2006 12:07:16 -0700 (PDT)
Received: by 10.35.121.2 with SMTP id y2mr4437195pym;
        Thu, 10 Aug 2006 12:07:16 -0700 (PDT)
Return-Path: <do-not-reply-C3270806@prdf.clientsection.com>
Received: from goshawk.37signals.com (goshawk.37signals.com [69.36.47.1])
        by mx.gmail.com with ESMTP id 38si3859126nzk.2006.08.10.12.07.16;
        Thu, 10 Aug 2006 12:07:16 -0700 (PDT)
Received-SPF: neutral (gmail.com: 69.36.47.1 is neither permitted nor denied by best guess record for domain of do-not-reply-C3270806@prdf.clientsection.com)
Received: from aconcagua.37signals.com (aconcagua.37signals.com [192.168.37.12])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by goshawk.37signals.com (Postfix) with ESMTP id D8E8B2E46A
	for <garrettsuchecki@gmail.com>; Thu, 10 Aug 2006 14:07:15 -0500 (CDT)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by aconcagua.37signals.com (Postfix) with ESMTP id 8D6A81CC52
	for <garrettsuchecki@gmail.com>; Thu, 10 Aug 2006 14:07:14 -0500 (CDT)
Date: Thu, 10 Aug 2006 14:07:13 -0500
From: Jeff Lennan <do-not-reply-C3270806@prdf.clientsection.com>
To: Garrett Suchecki <garrettsuchecki@gmail.com>
Subject: [SL] Re: Del.icio.us Bug
Content-Type: text/plain; charset=utf-8
Message-Id: <20060810190714.8D6A81CC52@aconcagua.37signals.com>

A new comment has been posted. DO NOT REPLY TO THIS EMAIL.
To post your own comment or read the original message, visit:
http://prdf.clientsection.com/P3090176

-----------------------------------------------------------------
Company: Silver Lining
Project: QA
-----------------------------------------------------------------
Jeff Lennan posted this comment:
.................................................................

   Testing summit. Cc'ing fred

   -----Original Message-----
   From: Fred Moyer <do-not-reply-C3269660@prdf.clientsection.com>
   Sent: Thu, 10 Aug 2006 12:59:28 Central Daylight Time
   To: Jeff Lennan <jeff@redhotpenguin.com>
   Subject: [SL] Re: Del.icio.us Bug

   A new comment has been posted. DO NOT REPLY TO THIS EMAIL.
   To post your own comment or read the original message, visit:
   http://prdf.clientsection.com/P3090176

   -----------------------------------------------------------------
   Company: Silver Lining
   Project: QA
   -----------------------------------------------------------------
   Fred Moyer posted this comment:
   .................................................................

   Thanks hans, I will try that link. - comment posted via summit
   (http://summit.redhotpenguin.com)

   --
   DO NOT REPLY TO THIS EMAIL
   To post a comment of your own, read the original message, or to
   read all existing comments, visit:
   http://prdf.clientsection.com/C3269660

   - comment posted via summit (http://summit.redhotpenguin.com)

--
DO NOT REPLY TO THIS EMAIL
To post a comment of your own, read the original message, or to
read all existing comments, visit:
http://prdf.clientsection.com/C3270806


--------------030908080909060200020902--

